let homInfo = {
    SUCCEEDED : "HOMEINFO_FETCH_SUCCEEDED",
    FAILED : "HOMEINFO_FETCH_FAILED",
    REQUESTED : "HOMEINFO_FETCH_REQUESTED",
    GETMORE:"GRID_FETCH_REQUESTED"
}
export default homInfo;