let movieList = {
    IsUpComming:{
        SUCCEEDED : "MOVIELIST_IsUpComming_FETCH_SUCCEEDED",
        FAILED : "MOVIELIST_IsUpComming_FETCH_FAILED",
        REQUESTED : "MOVIELIST_IsUpComming_FETCH_REQUESTED",
    },
    IsTrendWeekly:{
        SUCCEEDED : "MOVIELIST_IsTrendWeekly_FETCH_SUCCEEDED",
        FAILED : "MOVIELIST_IsTrendWeekly_FETCH_FAILED",
        REQUESTED : "MOVIELIST_IsTrendWeekly_FETCH_REQUESTED",
    },
    PostIDRelative:{
        SUCCEEDED : "MOVIELIST_PostIDRelative_FETCH_SUCCEEDED",
        FAILED : "MOVIELIST_PostIDRelative_FETCH_FAILED",
        REQUESTED : "MOVIELIST_PostIDRelative_FETCH_REQUESTED",
    },
    // Crew:{
    //     SUCCEEDED : "MOVIELIST_CREW_FETCH_SUCCEEDED",
    //     FAILED : "MOVIELIST_CREW_FETCH_FAILED",
    //     REQUESTED : "MOVIELIST_CREW_FETCH_REQUESTED",
    // }

    // SUCCEEDED : "MOVIELIST_FETCH_SUCCEEDED",
    // FAILED : "MOVIELIST_FETCH_FAILED",
    // REQUESTED : "MOVIELIST_FETCH_REQUESTED",

}
export default movieList;